### ISSUE TITLE
Templatize Readme Creation

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/roadrunner#22] opened 2016-02-02 20:10 UTC
Not sure what the best practice is here - aside from always needing 
- a consistent license
- a guide for "how to contribute"
- steps for set up and other normal things

Having a readme that people start with might be good enough, but we're pretty inconsistent about this as is.

**Comment by jeffmaher** [comment] 2016-02-16 17:07
Duplicate of: https://github.com/department-of-veterans-affairs/roadrunner-rails/issues/24

**Closed as completed** 2016-02-16 17:07 UTC
